version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  ezinfo-api:
    build:
      context: ./ezinfo.API
      dockerfile: Dockerfile-prod
    ports:
      - '3000:3000'
    container_name: ezinfo-api
    networks:
      - app-tier
    volumes:
      - ./ezinfo.API:/usr/src/app/ezinfo.API
      - /usr/src/app/ezinfo.API/node_modules
    depends_on:
      - mongodb
  ezinfo-spa:
    build:
      context: ./ezinfo.SPA
      dockerfile: Dockerfile-prod
    ports:
      - '4201:4201'
    expose:
      - '4201'
    container_name: ezinfo-spa
    volumes:
      - ./ezinfo.SPA:/usr/src/app/ezinfo.SPA
      - /usr/src/app/ezinfo.SPA/node_modules
  mongodb:
    image: mongo:6-jammy
    restart: always
    container_name: ezinfo_db
    networks:
      - app-tier
    environment:
      MONGO_INITDB_DATABASE: 'ezinfo'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - 'ezinfo-db:/var/lib/mongodb'
volumes:
  ezinfo-db:
