# Step 1: Build frontend
FROM node:18-alpine as builder

WORKDIR /usr/src/app/ezinfo.SPA

RUN chown -R root .

COPY package*.json ./

COPY . /usr/src/app/ezinfo.SPA/

RUN npm ci --omit=dev --force && npm install --save-dev @angular/cli@16.0.1 @angular-devkit/build-angular@16.0.1 --force

RUN npm run build --prod

# Step 2: Run nginx
FROM nginx:latest

COPY --from=builder /usr/src/app/ezinfo.SPA/dist/ezinfo-app /usr/share/nginx/html
COPY --from=builder /usr/src/app/ezinfo.SPA/ssl /usr/share/nginx/ssl
COPY --from=builder /usr/src/app/ezinfo.SPA/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4201
EXPOSE 443