FROM node:18-alpine

WORKDIR /usr/src/app/ezinfo.API

RUN chown -R root .

COPY --chown=node:node package*.json ./

COPY --chown=node:node tsconfig.json ./

COPY --chown=node:node . .

RUN npm ci --omit=dev && npm i -g @nestjs/cli

RUN npm run build

USER root

CMD ["node", "dist/src/main.js"]
